# Generated by Django 3.0.4 on 2020-03-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200320_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='push_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
