# Generated by Django 3.0.4 on 2020-03-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200321_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='category',
        ),
        migrations.AddField(
            model_name='customuser',
            name='_categories',
            field=models.ManyToManyField(blank=True, to='users.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='severity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
