# Generated by Django 3.0.4 on 2020-03-21 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200321_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='_contacts',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
