# Generated by Django 3.0.4 on 2020-03-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200321_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_separate',
            field=models.BooleanField(default=False),
        ),
    ]
