# Generated by Django 3.0.4 on 2020-03-21 23:43

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        user.randomized_id = uuid.uuid4()
        user.save(update_fields=['randomized_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_randomized_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
