# Generated by Django 3.0.4 on 2020-03-21 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200321_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='randomized_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
