# Generated by Django 3.0.4 on 2020-03-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200321_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sharepermission',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
